# -*- coding: utf-8 -*-
"""To-Do List Application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSt6U4WlLnD1RSmI3BS7r9aXIp-Ijcp5

1.Use lists to store tasks

2.Implement add/remove/view functionality

3.Store tasks in a text file using open()
"""

import os

TODO_FILE= "todo.txt"

def load_tasks():
    """Loads tasks from the todo.txt file."""
    tasks = []
    if os.path.exists(TODO_FILE):
        with open(TODO_FILE, "r") as file:
            for line in file:
                tasks.append(line.strip())
    return tasks

def save_tasks(tasks):
    """Saves tasks to the todo.txt file."""
    with open(TODO_FILE, "w") as file:
        for task in tasks:
            file.write(task + "\n")

def display_tasks(tasks):
    """Displays all current tasks with their numbers."""
    if not tasks:
        print("\nYour to-do list is empty!")
    else:
        print("\n--- Your To-Do List ---")
        for i, task in enumerate(tasks):
            print(f"{i + 1}. {task}")
        print("-----------------------")

def add_task(tasks):
    """Adds a new task to the list."""
    task = input("Enter the task to add: ").strip()
    if task:
        tasks.append(task)
        save_tasks(tasks)
        print(f"Task '{task}' added.")
    else:
        print("Task cannot be empty.")

def remove_task(tasks):
    """Removes a task from the list by its number."""
    display_tasks(tasks)
    if not tasks:
        return

    while True:
        try:
            task_num_str = input("Enter the number of the task to remove: ").strip()
            if not task_num_str:
                print("No task number entered. Returning to main menu.")
                return

            task_num = int(task_num_str)
            if 1 <= task_num <= len(tasks):
                removed_task = tasks.pop(task_num - 1)
                save_tasks(tasks)
                print(f"Task '{removed_task}' removed.")
                break
            else:
                print("Invalid task number. Please enter a valid number from the list.")
        except ValueError: #
            print("Invalid input. Please enter a number.")


def main():
    """Main function to run the To-Do List application."""
    tasks = load_tasks()

    while True:
        print("\n--- To-Do List Application ---")
        print("1. View tasks")
        print("2. Add task")
        print("3. Remove task")
        print("4. Exit")
        print("----------------------------")

        choice = input("Enter your choice (1-4): ").strip()

        if choice == '1':
            display_tasks(tasks)
        elif choice == '2':
            add_task(tasks)
        elif choice == '3':
            remove_task(tasks)
        elif choice == '4':
            print("Exiting To-Do List. Goodbye!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 4.")

if __name__ == "__main__":
    main()